version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - /opt/repos:/usr/share/nginx/html/download/rocky8
      - nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
